version: '3'

services:
  # Game server
  server:
    image: ${TLBB_SERVER_IMAGE_NAME}:${IMAGE_VERSION}
    container_name: tlbb_server
    volumes:
      - "${SERVER_DIR}/server:/home"
      - "${SERVER_DIR}/billing:/opt"
    ports:
      - "${LOGIN_PORT}:${LOGIN_PORT}"
      - "${SERVER_PORT}:${SERVER_PORT}"
      - "${BILLING_PORT}:${BILLING_PORT}"
    restart: always
    links:
      - tlbbdb
  # tlbb database
  tlbbdb:
    image: ${TLBBDB_IMAGE_NAME}:${IMAGE_VERSION}
    container_name: tlbb_db
    volumes:
      - "${SERVER_DIR}/tlbbdb/mysql:/var/lib/mysql"
    ports:
      - "${TLBB_MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${TLBB_MYSQL_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    restart: always
  # docker管理监控
  portainer:
    image: portainer/portainer:latest
    container_name: portainer
    ports:
      - "${PORTAINER_PORT}:9000" 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PORTAINER_CN}:/public
    restart: always
  # 注册接口
  #jdk:
  #  image: openjdk:8
  #  container_name: jdk
  #  volumes:
  #    - "${SERVER_DIR}/reg:/tmp"
  #  ports:
  #    - "12345:8888"
  #  working_dir: /tmp
  #  command: java -jar TLBBreg-0.0.1-SNAPSHOT.jar --server.port=8888 --spring.profiles.active=application.properties
  #  restart: always
  # 前端页面(官网)
  #tomcat:
  #  image: tomcat:7
  #  container_name: tomcat
  #  volumes:
  #   - "${SERVER_DIR}/tomcat:/usr/local/tomcat/webapps/ROOT"
  #  ports:
  #    - "${TOMCAT_PORT}:8080"
  #  restart: always